version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  relative-path-mode: cfg 

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/Nikolay-Yakunin/gouge)

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    - gosec
    - copyloopvar
    - wrapcheck
    - revive

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0
