// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"github.com/unclestep/Rogue/internal/application"
	"github.com/unclestep/Rogue/internal/application/usecase"
	"github.com/unclestep/Rogue/internal/application/view"
	"github.com/unclestep/Rogue/internal/domain/service"
	"github.com/unclestep/Rogue/internal/presentation/network"
)

// Injectors from wire.go:

// InitializeApp is the composition root for the standalone binary.
// Wire generates the function body in wire_gen.go.
func InitializeApp(cfg Config) *network.App {
	jsonPlaythroughRepo := provideJsonPlaythroughRepo(cfg)
	cachedPlaythroughRepo := provideCachedRepo(jsonPlaythroughRepo)
	jsonRulesRepo := provideJsonRulesRepo(cfg)
	impactResolver := service.NewImpactResolverService()
	pickup := service.NewPickupService()
	interactor := service.NewInteractorService()
	itemUsage := service.NewItemUsageService()
	combat := service.NewCombatService(impactResolver)
	movement := service.NewMovementService(impactResolver, pickup)
	pathfinder := service.NewPathfinderService()
	moveResolver := service.NewMoveResolverService()
	raycaster := service.NewRaycaster()
	fallbackPolicy := service.NewFallbackPolicy(pathfinder)
	monsterController := service.NewMonsterControllerService(pathfinder, moveResolver, raycaster, fallbackPolicy)
	topologyGenerator := service.NewTopologyGenerator()
	doorLocker := service.NewDoorLocker()
	resolveTurn := usecase.NewResolveTurn(cachedPlaythroughRepo, jsonRulesRepo, impactResolver, pickup, interactor, itemUsage, combat, movement, pathfinder, moveResolver, monsterController, raycaster, topologyGenerator, doorLocker)
	submitIntent := usecase.NewSubmitIntent(cachedPlaythroughRepo, moveResolver)
	resolveState := usecase.NewResolveState(cachedPlaythroughRepo, jsonRulesRepo, resolveTurn, submitIntent, raycaster)
	mapper := view.NewMapper(cachedPlaythroughRepo)
	gameLoop := application.NewGameLoop(resolveState, mapper)
	server := network.NewServer(gameLoop)
	client := network.NewClient()
	app := network.NewApp(server, client)
	return app
}
