// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire

//go:build !wireinject

package bootstrap

import (
	"github.com/unclestep/Rogue/internal/application"
	"github.com/unclestep/Rogue/internal/application/usecase"
	"github.com/unclestep/Rogue/internal/application/view"
	"github.com/unclestep/Rogue/internal/domain/service"
	"github.com/unclestep/Rogue/internal/infrastructure/storage"
	"github.com/unclestep/Rogue/internal/presentation/network"
)

// InitializeApp wires up the standalone application.
func InitializeApp(cfg Config) *network.App {
	// Infrastructure
	jsonPlaythroughRepo := provideJsonPlaythroughRepo(cfg)
	cachedPlaythroughRepo := storage.NewCachedPlaythroughRepo(jsonPlaythroughRepo)
	jsonRulesRepo := provideJsonRulesRepo(cfg)

	// Stateless domain services — allocated once for the lifetime of the process.
	impactResolver := service.NewImpactResolverService()
	pickup := service.NewPickupService()
	interactor := service.NewInteractorService()
	itemUsage := service.NewItemUsageService()
	combat := service.NewCombatService(impactResolver)
	movement := service.NewMovementService(impactResolver, pickup)
	pathfinder := service.NewPathfinderService()
	moveResolver := service.NewMoveResolverService()
	monsterController := service.NewMonsterControllerService(pathfinder, moveResolver)
	topologyGenerator := service.NewTopologyGenerator()
	doorLocker := service.NewDoorLocker()
	raycaster := service.NewRaycaster()

	// Use cases
	resolveTurn := usecase.NewResolveTurn(
		cachedPlaythroughRepo,
		jsonRulesRepo,
		impactResolver,
		pickup,
		interactor,
		itemUsage,
		combat,
		movement,
		pathfinder,
		moveResolver,
		monsterController,
		raycaster,
		topologyGenerator,
		doorLocker,
	)
	submitIntent := usecase.NewSubmitIntent(cachedPlaythroughRepo, moveResolver)
	resolveState := usecase.NewResolveState(cachedPlaythroughRepo, jsonRulesRepo, resolveTurn, submitIntent, raycaster)

	// Application layer
	mapper := view.NewMapper(cachedPlaythroughRepo)
	gameLoop := application.NewGameLoop(resolveState, mapper)

	// Presentation layer
	server := network.NewServer(gameLoop)
	client := network.NewClient()
	return network.NewApp(server, client)
}
