// Code generated by "enumer -type=AttackPatternType,MovePatternType,VitalType,AttrType,BehaviorType,TriggerType,TargetType,VisibilityState,TileType,GameState -output=enums_enumer.go ."; DO NOT EDIT.

package model

import (
	"fmt"
	"strings"
)

const _AttackPatternTypeName = "AttackPatternDefault"

var _AttackPatternTypeIndex = [...]uint8{0, 20}

const _AttackPatternTypeLowerName = "attackpatterndefault"

func (i AttackPatternType) String() string {
	if i < 0 || i >= AttackPatternType(len(_AttackPatternTypeIndex)-1) {
		return fmt.Sprintf("AttackPatternType(%d)", i)
	}
	return _AttackPatternTypeName[_AttackPatternTypeIndex[i]:_AttackPatternTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _AttackPatternTypeNoOp() {
	var x [1]struct{}
	_ = x[AttackPatternDefault-(0)]
}

var _AttackPatternTypeValues = []AttackPatternType{AttackPatternDefault}

var _AttackPatternTypeNameToValueMap = map[string]AttackPatternType{
	_AttackPatternTypeName[0:20]:      AttackPatternDefault,
	_AttackPatternTypeLowerName[0:20]: AttackPatternDefault,
}

var _AttackPatternTypeNames = []string{
	_AttackPatternTypeName[0:20],
}

// AttackPatternTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AttackPatternTypeString(s string) (AttackPatternType, error) {
	if val, ok := _AttackPatternTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _AttackPatternTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to AttackPatternType values", s)
}

// AttackPatternTypeValues returns all values of the enum
func AttackPatternTypeValues() []AttackPatternType {
	return _AttackPatternTypeValues
}

// AttackPatternTypeStrings returns a slice of all String values of the enum
func AttackPatternTypeStrings() []string {
	strs := make([]string, len(_AttackPatternTypeNames))
	copy(strs, _AttackPatternTypeNames)
	return strs
}

// IsAAttackPatternType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i AttackPatternType) IsAAttackPatternType() bool {
	for _, v := range _AttackPatternTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

const _MovePatternTypeName = "MovePatternDefaultMovePatternTeleportMovePatternDiagonal"

var _MovePatternTypeIndex = [...]uint8{0, 18, 37, 56}

const _MovePatternTypeLowerName = "movepatterndefaultmovepatternteleportmovepatterndiagonal"

func (i MovePatternType) String() string {
	if i < 0 || i >= MovePatternType(len(_MovePatternTypeIndex)-1) {
		return fmt.Sprintf("MovePatternType(%d)", i)
	}
	return _MovePatternTypeName[_MovePatternTypeIndex[i]:_MovePatternTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _MovePatternTypeNoOp() {
	var x [1]struct{}
	_ = x[MovePatternDefault-(0)]
	_ = x[MovePatternTeleport-(1)]
	_ = x[MovePatternDiagonal-(2)]
}

var _MovePatternTypeValues = []MovePatternType{MovePatternDefault, MovePatternTeleport, MovePatternDiagonal}

var _MovePatternTypeNameToValueMap = map[string]MovePatternType{
	_MovePatternTypeName[0:18]:       MovePatternDefault,
	_MovePatternTypeLowerName[0:18]:  MovePatternDefault,
	_MovePatternTypeName[18:37]:      MovePatternTeleport,
	_MovePatternTypeLowerName[18:37]: MovePatternTeleport,
	_MovePatternTypeName[37:56]:      MovePatternDiagonal,
	_MovePatternTypeLowerName[37:56]: MovePatternDiagonal,
}

var _MovePatternTypeNames = []string{
	_MovePatternTypeName[0:18],
	_MovePatternTypeName[18:37],
	_MovePatternTypeName[37:56],
}

// MovePatternTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func MovePatternTypeString(s string) (MovePatternType, error) {
	if val, ok := _MovePatternTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _MovePatternTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to MovePatternType values", s)
}

// MovePatternTypeValues returns all values of the enum
func MovePatternTypeValues() []MovePatternType {
	return _MovePatternTypeValues
}

// MovePatternTypeStrings returns a slice of all String values of the enum
func MovePatternTypeStrings() []string {
	strs := make([]string, len(_MovePatternTypeNames))
	copy(strs, _MovePatternTypeNames)
	return strs
}

// IsAMovePatternType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i MovePatternType) IsAMovePatternType() bool {
	for _, v := range _MovePatternTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

const _VitalTypeName = "VitalUnknownVitalHPVitalStamina"

var _VitalTypeIndex = [...]uint8{0, 12, 19, 31}

const _VitalTypeLowerName = "vitalunknownvitalhpvitalstamina"

func (i VitalType) String() string {
	if i < 0 || i >= VitalType(len(_VitalTypeIndex)-1) {
		return fmt.Sprintf("VitalType(%d)", i)
	}
	return _VitalTypeName[_VitalTypeIndex[i]:_VitalTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _VitalTypeNoOp() {
	var x [1]struct{}
	_ = x[VitalUnknown-(0)]
	_ = x[VitalHP-(1)]
	_ = x[VitalStamina-(2)]
}

var _VitalTypeValues = []VitalType{VitalUnknown, VitalHP, VitalStamina}

var _VitalTypeNameToValueMap = map[string]VitalType{
	_VitalTypeName[0:12]:       VitalUnknown,
	_VitalTypeLowerName[0:12]:  VitalUnknown,
	_VitalTypeName[12:19]:      VitalHP,
	_VitalTypeLowerName[12:19]: VitalHP,
	_VitalTypeName[19:31]:      VitalStamina,
	_VitalTypeLowerName[19:31]: VitalStamina,
}

var _VitalTypeNames = []string{
	_VitalTypeName[0:12],
	_VitalTypeName[12:19],
	_VitalTypeName[19:31],
}

// VitalTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func VitalTypeString(s string) (VitalType, error) {
	if val, ok := _VitalTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _VitalTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to VitalType values", s)
}

// VitalTypeValues returns all values of the enum
func VitalTypeValues() []VitalType {
	return _VitalTypeValues
}

// VitalTypeStrings returns a slice of all String values of the enum
func VitalTypeStrings() []string {
	strs := make([]string, len(_VitalTypeNames))
	copy(strs, _VitalTypeNames)
	return strs
}

// IsAVitalType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i VitalType) IsAVitalType() bool {
	for _, v := range _VitalTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

const _AttrTypeName = "AttrUnknownAttrMaxHPAttrMaxStaminaAttrAttackStaminaCostAttrMoveStaminaCostAttrActionStaminaCostAttrStaminaRegenAttrStrengthAttrDexterityAttrHostilityAttrCounterAttackChance"

var _AttrTypeIndex = [...]uint8{0, 11, 20, 34, 55, 74, 95, 111, 123, 136, 149, 172}

const _AttrTypeLowerName = "attrunknownattrmaxhpattrmaxstaminaattrattackstaminacostattrmovestaminacostattractionstaminacostattrstaminaregenattrstrengthattrdexterityattrhostilityattrcounterattackchance"

func (i AttrType) String() string {
	if i < 0 || i >= AttrType(len(_AttrTypeIndex)-1) {
		return fmt.Sprintf("AttrType(%d)", i)
	}
	return _AttrTypeName[_AttrTypeIndex[i]:_AttrTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _AttrTypeNoOp() {
	var x [1]struct{}
	_ = x[AttrUnknown-(0)]
	_ = x[AttrMaxHP-(1)]
	_ = x[AttrMaxStamina-(2)]
	_ = x[AttrAttackStaminaCost-(3)]
	_ = x[AttrMoveStaminaCost-(4)]
	_ = x[AttrActionStaminaCost-(5)]
	_ = x[AttrStaminaRegen-(6)]
	_ = x[AttrStrength-(7)]
	_ = x[AttrDexterity-(8)]
	_ = x[AttrHostility-(9)]
	_ = x[AttrCounterAttackChance-(10)]
}

var _AttrTypeValues = []AttrType{AttrUnknown, AttrMaxHP, AttrMaxStamina, AttrAttackStaminaCost, AttrMoveStaminaCost, AttrActionStaminaCost, AttrStaminaRegen, AttrStrength, AttrDexterity, AttrHostility, AttrCounterAttackChance}

var _AttrTypeNameToValueMap = map[string]AttrType{
	_AttrTypeName[0:11]:         AttrUnknown,
	_AttrTypeLowerName[0:11]:    AttrUnknown,
	_AttrTypeName[11:20]:        AttrMaxHP,
	_AttrTypeLowerName[11:20]:   AttrMaxHP,
	_AttrTypeName[20:34]:        AttrMaxStamina,
	_AttrTypeLowerName[20:34]:   AttrMaxStamina,
	_AttrTypeName[34:55]:        AttrAttackStaminaCost,
	_AttrTypeLowerName[34:55]:   AttrAttackStaminaCost,
	_AttrTypeName[55:74]:        AttrMoveStaminaCost,
	_AttrTypeLowerName[55:74]:   AttrMoveStaminaCost,
	_AttrTypeName[74:95]:        AttrActionStaminaCost,
	_AttrTypeLowerName[74:95]:   AttrActionStaminaCost,
	_AttrTypeName[95:111]:       AttrStaminaRegen,
	_AttrTypeLowerName[95:111]:  AttrStaminaRegen,
	_AttrTypeName[111:123]:      AttrStrength,
	_AttrTypeLowerName[111:123]: AttrStrength,
	_AttrTypeName[123:136]:      AttrDexterity,
	_AttrTypeLowerName[123:136]: AttrDexterity,
	_AttrTypeName[136:149]:      AttrHostility,
	_AttrTypeLowerName[136:149]: AttrHostility,
	_AttrTypeName[149:172]:      AttrCounterAttackChance,
	_AttrTypeLowerName[149:172]: AttrCounterAttackChance,
}

var _AttrTypeNames = []string{
	_AttrTypeName[0:11],
	_AttrTypeName[11:20],
	_AttrTypeName[20:34],
	_AttrTypeName[34:55],
	_AttrTypeName[55:74],
	_AttrTypeName[74:95],
	_AttrTypeName[95:111],
	_AttrTypeName[111:123],
	_AttrTypeName[123:136],
	_AttrTypeName[136:149],
	_AttrTypeName[149:172],
}

// AttrTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AttrTypeString(s string) (AttrType, error) {
	if val, ok := _AttrTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _AttrTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to AttrType values", s)
}

// AttrTypeValues returns all values of the enum
func AttrTypeValues() []AttrType {
	return _AttrTypeValues
}

// AttrTypeStrings returns a slice of all String values of the enum
func AttrTypeStrings() []string {
	strs := make([]string, len(_AttrTypeNames))
	copy(strs, _AttrTypeNames)
	return strs
}

// IsAAttrType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i AttrType) IsAAttrType() bool {
	for _, v := range _AttrTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

const _BehaviorTypeName = "BehaviorWanderBehaviorChase"

var _BehaviorTypeIndex = [...]uint8{0, 14, 27}

const _BehaviorTypeLowerName = "behaviorwanderbehaviorchase"

func (i BehaviorType) String() string {
	if i < 0 || i >= BehaviorType(len(_BehaviorTypeIndex)-1) {
		return fmt.Sprintf("BehaviorType(%d)", i)
	}
	return _BehaviorTypeName[_BehaviorTypeIndex[i]:_BehaviorTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _BehaviorTypeNoOp() {
	var x [1]struct{}
	_ = x[BehaviorWander-(0)]
	_ = x[BehaviorChase-(1)]
}

var _BehaviorTypeValues = []BehaviorType{BehaviorWander, BehaviorChase}

var _BehaviorTypeNameToValueMap = map[string]BehaviorType{
	_BehaviorTypeName[0:14]:       BehaviorWander,
	_BehaviorTypeLowerName[0:14]:  BehaviorWander,
	_BehaviorTypeName[14:27]:      BehaviorChase,
	_BehaviorTypeLowerName[14:27]: BehaviorChase,
}

var _BehaviorTypeNames = []string{
	_BehaviorTypeName[0:14],
	_BehaviorTypeName[14:27],
}

// BehaviorTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func BehaviorTypeString(s string) (BehaviorType, error) {
	if val, ok := _BehaviorTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _BehaviorTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to BehaviorType values", s)
}

// BehaviorTypeValues returns all values of the enum
func BehaviorTypeValues() []BehaviorType {
	return _BehaviorTypeValues
}

// BehaviorTypeStrings returns a slice of all String values of the enum
func BehaviorTypeStrings() []string {
	strs := make([]string, len(_BehaviorTypeNames))
	copy(strs, _BehaviorTypeNames)
	return strs
}

// IsABehaviorType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i BehaviorType) IsABehaviorType() bool {
	for _, v := range _BehaviorTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

const _TriggerTypeName = "TriggerNotSpecifiedTriggerOnPreHitTriggerOnHitTriggerOnDamageTriggerOnMoveTriggerEffectOnExpireTriggerEffectOnTurn"

var _TriggerTypeIndex = [...]uint8{0, 19, 34, 46, 61, 74, 95, 114}

const _TriggerTypeLowerName = "triggernotspecifiedtriggeronprehittriggeronhittriggerondamagetriggeronmovetriggereffectonexpiretriggereffectonturn"

func (i TriggerType) String() string {
	if i < 0 || i >= TriggerType(len(_TriggerTypeIndex)-1) {
		return fmt.Sprintf("TriggerType(%d)", i)
	}
	return _TriggerTypeName[_TriggerTypeIndex[i]:_TriggerTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TriggerTypeNoOp() {
	var x [1]struct{}
	_ = x[TriggerNotSpecified-(0)]
	_ = x[TriggerOnPreHit-(1)]
	_ = x[TriggerOnHit-(2)]
	_ = x[TriggerOnDamage-(3)]
	_ = x[TriggerOnMove-(4)]
	_ = x[TriggerEffectOnExpire-(5)]
	_ = x[TriggerEffectOnTurn-(6)]
}

var _TriggerTypeValues = []TriggerType{TriggerNotSpecified, TriggerOnPreHit, TriggerOnHit, TriggerOnDamage, TriggerOnMove, TriggerEffectOnExpire, TriggerEffectOnTurn}

var _TriggerTypeNameToValueMap = map[string]TriggerType{
	_TriggerTypeName[0:19]:        TriggerNotSpecified,
	_TriggerTypeLowerName[0:19]:   TriggerNotSpecified,
	_TriggerTypeName[19:34]:       TriggerOnPreHit,
	_TriggerTypeLowerName[19:34]:  TriggerOnPreHit,
	_TriggerTypeName[34:46]:       TriggerOnHit,
	_TriggerTypeLowerName[34:46]:  TriggerOnHit,
	_TriggerTypeName[46:61]:       TriggerOnDamage,
	_TriggerTypeLowerName[46:61]:  TriggerOnDamage,
	_TriggerTypeName[61:74]:       TriggerOnMove,
	_TriggerTypeLowerName[61:74]:  TriggerOnMove,
	_TriggerTypeName[74:95]:       TriggerEffectOnExpire,
	_TriggerTypeLowerName[74:95]:  TriggerEffectOnExpire,
	_TriggerTypeName[95:114]:      TriggerEffectOnTurn,
	_TriggerTypeLowerName[95:114]: TriggerEffectOnTurn,
}

var _TriggerTypeNames = []string{
	_TriggerTypeName[0:19],
	_TriggerTypeName[19:34],
	_TriggerTypeName[34:46],
	_TriggerTypeName[46:61],
	_TriggerTypeName[61:74],
	_TriggerTypeName[74:95],
	_TriggerTypeName[95:114],
}

// TriggerTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TriggerTypeString(s string) (TriggerType, error) {
	if val, ok := _TriggerTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TriggerTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TriggerType values", s)
}

// TriggerTypeValues returns all values of the enum
func TriggerTypeValues() []TriggerType {
	return _TriggerTypeValues
}

// TriggerTypeStrings returns a slice of all String values of the enum
func TriggerTypeStrings() []string {
	strs := make([]string, len(_TriggerTypeNames))
	copy(strs, _TriggerTypeNames)
	return strs
}

// IsATriggerType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TriggerType) IsATriggerType() bool {
	for _, v := range _TriggerTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

const _TargetTypeName = "TargetNotSpecifiedTargetOpponentTargetSource"

var _TargetTypeIndex = [...]uint8{0, 18, 32, 44}

const _TargetTypeLowerName = "targetnotspecifiedtargetopponenttargetsource"

func (i TargetType) String() string {
	if i < 0 || i >= TargetType(len(_TargetTypeIndex)-1) {
		return fmt.Sprintf("TargetType(%d)", i)
	}
	return _TargetTypeName[_TargetTypeIndex[i]:_TargetTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TargetTypeNoOp() {
	var x [1]struct{}
	_ = x[TargetNotSpecified-(0)]
	_ = x[TargetOpponent-(1)]
	_ = x[TargetSource-(2)]
}

var _TargetTypeValues = []TargetType{TargetNotSpecified, TargetOpponent, TargetSource}

var _TargetTypeNameToValueMap = map[string]TargetType{
	_TargetTypeName[0:18]:       TargetNotSpecified,
	_TargetTypeLowerName[0:18]:  TargetNotSpecified,
	_TargetTypeName[18:32]:      TargetOpponent,
	_TargetTypeLowerName[18:32]: TargetOpponent,
	_TargetTypeName[32:44]:      TargetSource,
	_TargetTypeLowerName[32:44]: TargetSource,
}

var _TargetTypeNames = []string{
	_TargetTypeName[0:18],
	_TargetTypeName[18:32],
	_TargetTypeName[32:44],
}

// TargetTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TargetTypeString(s string) (TargetType, error) {
	if val, ok := _TargetTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TargetTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TargetType values", s)
}

// TargetTypeValues returns all values of the enum
func TargetTypeValues() []TargetType {
	return _TargetTypeValues
}

// TargetTypeStrings returns a slice of all String values of the enum
func TargetTypeStrings() []string {
	strs := make([]string, len(_TargetTypeNames))
	copy(strs, _TargetTypeNames)
	return strs
}

// IsATargetType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TargetType) IsATargetType() bool {
	for _, v := range _TargetTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

const _VisibilityStateName = "UnexploredExploredVisible"

var _VisibilityStateIndex = [...]uint8{0, 10, 18, 25}

const _VisibilityStateLowerName = "unexploredexploredvisible"

func (i VisibilityState) String() string {
	if i < 0 || i >= VisibilityState(len(_VisibilityStateIndex)-1) {
		return fmt.Sprintf("VisibilityState(%d)", i)
	}
	return _VisibilityStateName[_VisibilityStateIndex[i]:_VisibilityStateIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _VisibilityStateNoOp() {
	var x [1]struct{}
	_ = x[Unexplored-(0)]
	_ = x[Explored-(1)]
	_ = x[Visible-(2)]
}

var _VisibilityStateValues = []VisibilityState{Unexplored, Explored, Visible}

var _VisibilityStateNameToValueMap = map[string]VisibilityState{
	_VisibilityStateName[0:10]:       Unexplored,
	_VisibilityStateLowerName[0:10]:  Unexplored,
	_VisibilityStateName[10:18]:      Explored,
	_VisibilityStateLowerName[10:18]: Explored,
	_VisibilityStateName[18:25]:      Visible,
	_VisibilityStateLowerName[18:25]: Visible,
}

var _VisibilityStateNames = []string{
	_VisibilityStateName[0:10],
	_VisibilityStateName[10:18],
	_VisibilityStateName[18:25],
}

// VisibilityStateString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func VisibilityStateString(s string) (VisibilityState, error) {
	if val, ok := _VisibilityStateNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _VisibilityStateNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to VisibilityState values", s)
}

// VisibilityStateValues returns all values of the enum
func VisibilityStateValues() []VisibilityState {
	return _VisibilityStateValues
}

// VisibilityStateStrings returns a slice of all String values of the enum
func VisibilityStateStrings() []string {
	strs := make([]string, len(_VisibilityStateNames))
	copy(strs, _VisibilityStateNames)
	return strs
}

// IsAVisibilityState returns "true" if the value is listed in the enum definition. "false" otherwise
func (i VisibilityState) IsAVisibilityState() bool {
	for _, v := range _VisibilityStateValues {
		if i == v {
			return true
		}
	}
	return false
}

const _TileTypeName = "EmptyWallFloorOpenDoorClosedDoorCorridorExit"

var _TileTypeIndex = [...]uint8{0, 5, 9, 14, 22, 32, 40, 44}

const _TileTypeLowerName = "emptywallflooropendoorcloseddoorcorridorexit"

func (i TileType) String() string {
	if i < 0 || i >= TileType(len(_TileTypeIndex)-1) {
		return fmt.Sprintf("TileType(%d)", i)
	}
	return _TileTypeName[_TileTypeIndex[i]:_TileTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TileTypeNoOp() {
	var x [1]struct{}
	_ = x[Empty-(0)]
	_ = x[Wall-(1)]
	_ = x[Floor-(2)]
	_ = x[OpenDoor-(3)]
	_ = x[ClosedDoor-(4)]
	_ = x[Corridor-(5)]
	_ = x[Exit-(6)]
}

var _TileTypeValues = []TileType{Empty, Wall, Floor, OpenDoor, ClosedDoor, Corridor, Exit}

var _TileTypeNameToValueMap = map[string]TileType{
	_TileTypeName[0:5]:        Empty,
	_TileTypeLowerName[0:5]:   Empty,
	_TileTypeName[5:9]:        Wall,
	_TileTypeLowerName[5:9]:   Wall,
	_TileTypeName[9:14]:       Floor,
	_TileTypeLowerName[9:14]:  Floor,
	_TileTypeName[14:22]:      OpenDoor,
	_TileTypeLowerName[14:22]: OpenDoor,
	_TileTypeName[22:32]:      ClosedDoor,
	_TileTypeLowerName[22:32]: ClosedDoor,
	_TileTypeName[32:40]:      Corridor,
	_TileTypeLowerName[32:40]: Corridor,
	_TileTypeName[40:44]:      Exit,
	_TileTypeLowerName[40:44]: Exit,
}

var _TileTypeNames = []string{
	_TileTypeName[0:5],
	_TileTypeName[5:9],
	_TileTypeName[9:14],
	_TileTypeName[14:22],
	_TileTypeName[22:32],
	_TileTypeName[32:40],
	_TileTypeName[40:44],
}

// TileTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TileTypeString(s string) (TileType, error) {
	if val, ok := _TileTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TileTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TileType values", s)
}

// TileTypeValues returns all values of the enum
func TileTypeValues() []TileType {
	return _TileTypeValues
}

// TileTypeStrings returns a slice of all String values of the enum
func TileTypeStrings() []string {
	strs := make([]string, len(_TileTypeNames))
	copy(strs, _TileTypeNames)
	return strs
}

// IsATileType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TileType) IsATileType() bool {
	for _, v := range _TileTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

const _GameStateName = "LobbyGameStatePlayingGameStateGameOverGameState"

var _GameStateIndex = [...]uint8{0, 14, 30, 47}

const _GameStateLowerName = "lobbygamestateplayinggamestategameovergamestate"

func (i GameState) String() string {
	if i < 0 || i >= GameState(len(_GameStateIndex)-1) {
		return fmt.Sprintf("GameState(%d)", i)
	}
	return _GameStateName[_GameStateIndex[i]:_GameStateIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _GameStateNoOp() {
	var x [1]struct{}
	_ = x[LobbyGameState-(0)]
	_ = x[PlayingGameState-(1)]
	_ = x[GameOverGameState-(2)]
}

var _GameStateValues = []GameState{LobbyGameState, PlayingGameState, GameOverGameState}

var _GameStateNameToValueMap = map[string]GameState{
	_GameStateName[0:14]:       LobbyGameState,
	_GameStateLowerName[0:14]:  LobbyGameState,
	_GameStateName[14:30]:      PlayingGameState,
	_GameStateLowerName[14:30]: PlayingGameState,
	_GameStateName[30:47]:      GameOverGameState,
	_GameStateLowerName[30:47]: GameOverGameState,
}

var _GameStateNames = []string{
	_GameStateName[0:14],
	_GameStateName[14:30],
	_GameStateName[30:47],
}

// GameStateString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func GameStateString(s string) (GameState, error) {
	if val, ok := _GameStateNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _GameStateNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to GameState values", s)
}

// GameStateValues returns all values of the enum
func GameStateValues() []GameState {
	return _GameStateValues
}

// GameStateStrings returns a slice of all String values of the enum
func GameStateStrings() []string {
	strs := make([]string, len(_GameStateNames))
	copy(strs, _GameStateNames)
	return strs
}

// IsAGameState returns "true" if the value is listed in the enum definition. "false" otherwise
func (i GameState) IsAGameState() bool {
	for _, v := range _GameStateValues {
		if i == v {
			return true
		}
	}
	return false
}
