package usecase_test

import (
	"testing"

	"github.com/unclestep/Rogue/internal/domain/model"
)

// TestResolveTurnNonPlayingStateReturnsCurrentState verifies that Execute does
// not process a turn when the playthrough is not in PlayingGameState.
func TestResolveTurnNonPlayingStateReturnsCurrentState(t *testing.T) {
	playRepo, rulesRepo := newTestRepos()
	rt := buildResolveTurn(playRepo, rulesRepo)

	// Create a session that is still in Lobby state.
	p := playRepo.Create(model.DefaultRulesId, 42)
	// Lobby is the default state — no dungeon, no processing expected.

	state := rt.Execute(p.PlaythroughId)

	if state != model.LobbyGameState {
		t.Errorf("Expected LobbyGameState for non-playing session, got %v", state)
	}
}

// TestResolveTurnUnknownIdReturnsLobby verifies that Execute does not panic
// when the requested PlaythroughId is not found, and returns LobbyGameState.
func TestResolveTurnUnknownIdReturnsLobby(t *testing.T) {
	playRepo, rulesRepo := newTestRepos()
	rt := buildResolveTurn(playRepo, rulesRepo)

	state := rt.Execute("completely-unknown-id")

	if state != model.LobbyGameState {
		t.Errorf("Expected LobbyGameState for unknown ID, got %v", state)
	}
}

// TestResolveTurnAllPlayersDeadReturnsGameOver verifies that Execute transitions
// to GameOverGameState when all players are dead (or there are no players).
// AreAllPlayersDead returns true for an empty Players map (0 == 0), so a session
// in PlayingGameState with no players triggers the game-over path without requiring
// player setup.
func TestResolveTurnAllPlayersDeadReturnsGameOver(t *testing.T) {
	playRepo, rulesRepo := newTestRepos()
	rt := buildResolveTurn(playRepo, rulesRepo)

	// Create a session and force it into Playing state with no players.
	// The dungeon will be generated by Execute (safety net), then
	// AreAllPlayersDead() returns true for the empty Players map.
	p := playRepo.Create(model.DefaultRulesId, 42)
	p.State = model.PlayingGameState
	playRepo.Save(p)

	state := rt.Execute(p.PlaythroughId)

	if state != model.GameOverGameState {
		t.Errorf("Expected GameOverGameState when all players are dead, got %v", state)
	}
}
